# Adapted from https://github.com/amirisback/automated-build-android-app-with-github-action
name: Build Debug APK

on:
  # push:
  #   branches:
  #     - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get the repository files
        uses: actions/checkout@v3

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Set gradlew as executable
        # for some reason the gradle-build-action doesn't do this automatically
        run: chmod +x ./gradlew

      - name: Build & assemble with gradle
        run: ./gradlew assembleDebug

-     - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
